import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { D_PERFECT, D_ZERO, scoreAttempt } from './score'
import type { SignRecording } from '../vision/types'

/**
 * Empirical calibration of the score scale.
 *
 * The corpus records several takes of each sign by the same signer. Two takes
 * of one sign are the *same sign performed correctly twice*, differing only by
 * natural variation; takes of different signs are a wrong-sign attempt. That
 * gives labelled positives and negatives without any expert annotation, which
 * is what the distance→score anchors in score.ts should be fitted to rather
 * than guessed.
 *
 * WHAT THIS DOES AND DOES NOT ESTABLISH
 * -------------------------------------
 * It measures how the scorer separates *a correct rendition* from *a different
 * sign*, and therefore where the score scale should sit for a correct attempt.
 *
 * It does NOT measure grading of a learner's imperfect rendition. All takes
 * here come from one fluent signer, so their spread is narrower than a
 * learner's would be — thresholds derived here are optimistic. Real learner
 * attempts judged by an SSL teacher are still required for the proposal's
 * ≥90%-accuracy-vs-expert claim; this establishes the scale, not that claim.
 *
 * Generate the data with:
 *   python tools/convert_references.py --dataset "<...>" --all \
 *     --only "$(cat tools/calibration_signs.txt)" --all-takes-out ../web/calibration
 */
const CALIBRATION_DIR = join(process.cwd(), 'calibration')

interface Take {
  gloss: string
  recording: SignRecording
}

function loadTakes(): Take[] {
  let names: string[]
  try {
    names = readdirSync(CALIBRATION_DIR).filter((n) => n.endsWith('.json'))
  } catch {
    return []
  }
  return names.map((name) => {
    const recording = JSON.parse(
      readFileSync(join(CALIBRATION_DIR, name), 'utf8'),
    ) as SignRecording
    return { gloss: recording.gloss, recording }
  })
}

const takes = loadTakes()
const byGloss = new Map<string, Take[]>()
for (const t of takes) {
  byGloss.set(t.gloss, [...(byGloss.get(t.gloss) ?? []), t])
}
// Only glosses with at least two takes can produce a positive pair.
const usable = [...byGloss.entries()].filter(([, ts]) => ts.length >= 2)

const hasData = usable.length >= 2
const describeCalibration = hasData ? describe : describe.skip

function percentile(sorted: number[], p: number): number {
  if (sorted.length === 0) return NaN
  const i = Math.min(sorted.length - 1, Math.max(0, Math.round((p / 100) * (sorted.length - 1))))
  return sorted[i]
}

describeCalibration('score-scale calibration', () => {
  // Positives: take vs a *different* take of the same sign.
  // Negatives: take vs the first take of a different sign.
  const positives: number[] = [] // DTW distance, not score — the score saturates
  const negatives: number[] = []

  for (const [gloss, ts] of usable) {
    for (let i = 1; i < ts.length; i++) {
      positives.push(scoreAttempt(ts[i].recording, ts[0].recording).normalizedDistance)
    }
    for (const [otherGloss, others] of usable) {
      if (otherGloss === gloss) continue
      negatives.push(scoreAttempt(ts[0].recording, others[0].recording).normalizedDistance)
    }
  }

  const finite = (xs: number[]) => xs.filter((x) => Number.isFinite(x))
  const posSorted = finite(positives).sort((a, b) => a - b)
  const negSorted = finite(negatives).sort((a, b) => a - b)
  const mean = (xs: number[]) => xs.reduce((a, b) => a + b, 0) / xs.length

  it('writes the calibration report', () => {
    // Written to a file rather than only logged: these figures belong in the
    // report, and a run's numbers should survive the terminal scrollback.
    const row = (label: string, xs: number[]) =>
      `| ${label} | ${xs.length} | ${mean(xs).toFixed(3)} | ${percentile(xs, 10).toFixed(3)} | ` +
      `${percentile(xs, 50).toFixed(3)} | ${percentile(xs, 90).toFixed(3)} |`

    const all = [...posSorted, ...negSorted].sort((a, b) => a - b)
    let bestAccuracy = 0
    let bestCut = 0
    for (const cut of all) {
      const correct =
        posSorted.filter((d) => d <= cut).length + negSorted.filter((d) => d > cut).length
      const accuracy = correct / (posSorted.length + negSorted.length)
      if (accuracy > bestAccuracy) {
        bestAccuracy = accuracy
        bestCut = cut
      }
    }

    writeFileSync(
      join(process.cwd(), 'calibration-report.md'),
      [
        '# Score-scale calibration',
        '',
        'Generated by `src/scoring/calibration.test.ts`. Do not edit by hand.',
        '',
        `Calibration set: **${usable.length} signs, ${takes.length} takes** from the`,
        'Yohan Abhishek corpus (CC BY-NC-SA 4.0), one fluent signer.',
        '',
        '## DTW distance distributions',
        '',
        '| pair | n | mean | p10 | median | p90 |',
        '|---|---|---|---|---|---|',
        row('same sign, another take', posSorted),
        row('a different sign', negSorted),
        '',
        '## Separation',
        '',
        `Best single cut-off: distance **${bestCut.toFixed(3)}** →`,
        `**${(bestAccuracy * 100).toFixed(1)}%** accuracy distinguishing a correct`,
        'rendition from a different sign.',
        '',
        '## Score anchors',
        '',
        `Current: \`D_PERFECT\` ${D_PERFECT}, \`D_ZERO\` ${D_ZERO}.`,
        '',
        `A correct rendition has median distance **${percentile(posSorted, 50).toFixed(3)}**.`,
        Number(percentile(posSorted, 50)) > D_ZERO
          ? '> **That is above `D_ZERO`, so a correct rendition currently scores 0.** ' +
            'The anchors were guessed before any data existed and need replacing.'
          : 'The anchors sit sensibly relative to the data.',
        '',
        '## Limitation',
        '',
        'Every take here is by one fluent signer, so this spread is *natural variation',
        "of a correct rendition* — narrower than a learner's would be. This establishes",
        'where the score scale should sit; it does **not** substantiate the proposal\'s',
        '≥90%-accuracy-vs-expert claim, which needs real learner attempts graded by an',
        'SSL teacher.',
        '',
      ].join('\n'),
      'utf8',
    )
    expect(bestAccuracy).toBeGreaterThan(0)
  })

  it('reports the empirical distance distributions', () => {
    // The measurement itself. These are the numbers the score anchors in
    // score.ts should be derived from, and what the report should quote.
    const fmt = (xs: number[]) =>
      `mean ${mean(xs).toFixed(3)}  p10 ${percentile(xs, 10).toFixed(3)}  ` +
      `median ${percentile(xs, 50).toFixed(3)}  p90 ${percentile(xs, 90).toFixed(3)}`
    console.log(
      [
        '',
        `  calibration set: ${usable.length} signs, ${takes.length} takes`,
        `  same sign, another take  n=${posSorted.length}  ${fmt(posSorted)}`,
        `  a different sign         n=${negSorted.length}  ${fmt(negSorted)}`,
        '',
        `  current anchors: D_PERFECT ${D_PERFECT}  D_ZERO ${D_ZERO}`,
        `  suggested:       D_PERFECT ${percentile(posSorted, 25).toFixed(2)}  ` +
          `D_ZERO ${percentile(negSorted, 25).toFixed(2)}`,
        '    (a correct rendition should score near full marks; a different sign near zero)',
      ].join('\n'),
    )
    expect(posSorted.length).toBeGreaterThan(0)
    expect(negSorted.length).toBeGreaterThan(0)
  })

  it('puts a correct rendition closer than a different sign', () => {
    expect(mean(posSorted)).toBeLessThan(mean(negSorted))
  })

  it('separates correct renditions from different signs', () => {
    // Best single cut-off on distance, and the accuracy it achieves. This is
    // the figure the ≥90% target is measured against once real learner
    // attempts, graded by an SSL teacher, replace this stand-in.
    const all = [...posSorted, ...negSorted].sort((a, b) => a - b)
    let bestAccuracy = 0
    let bestCut = 0
    for (const cut of all) {
      const correct =
        posSorted.filter((d) => d <= cut).length + negSorted.filter((d) => d > cut).length
      const accuracy = correct / (posSorted.length + negSorted.length)
      if (accuracy > bestAccuracy) {
        bestAccuracy = accuracy
        bestCut = cut
      }
    }
    console.log(
      `\n  best separation: distance ${bestCut.toFixed(3)} → ` +
        `${(bestAccuracy * 100).toFixed(1)}% accuracy\n`,
    )
    // Deliberately a floor, not a target: this guards against a regression in
    // the scorer, and is not the proposal's ≥90%-vs-expert claim.
    expect(bestAccuracy).toBeGreaterThan(0.7)
  })
})
