import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { DEFAULT_WEIGHTS, scoreAttempt } from './score'
import type { DistanceWeights } from './score'
import type { SignRecording } from '../vision/types'

/**
 * Fits the handshape/trajectory weighting to data instead of assuming it.
 *
 * The two blocks were split 0.7/0.3 on the reasoning that handshape is the
 * stronger cue — plausible, but never measured. The calibration corpus labels
 * itself (takes of one sign are correct renditions; takes of different signs
 * are wrong-sign attempts), so the split can simply be searched for the value
 * that best separates those two populations.
 *
 * Weights are constrained to sum to 1 so the distance scale stays comparable
 * and the score anchors keep their meaning.
 *
 * Run: npx vitest run weights.fit
 */
const CALIBRATION_DIR = join(process.cwd(), 'calibration')
const MIN_TAKES = 4
const MAX_SIGNS = 24 // keeps the grid search to a few minutes

interface Take {
  gloss: string
  recording: SignRecording
}

function loadTakes(): Take[] {
  let files: string[]
  try {
    files = readdirSync(CALIBRATION_DIR).filter((n) => n.endsWith('.json'))
  } catch {
    return []
  }
  return files.map((name) => {
    const rec = JSON.parse(readFileSync(join(CALIBRATION_DIR, name), 'utf8')) as SignRecording
    return { gloss: rec.gloss, recording: rec }
  })
}

const takes = loadTakes()
const byGloss = new Map<string, Take[]>()
for (const t of takes) {
  const list = byGloss.get(t.gloss) ?? []
  list.push(t)
  byGloss.set(t.gloss, list)
}
const usable = [...byGloss.entries()]
  .filter(([, ts]) => ts.length >= MIN_TAKES)
  .slice(0, MAX_SIGNS)

const describeFit = usable.length >= 6 ? describe : describe.skip

/** Best achievable accuracy separating same-sign pairs from different-sign pairs. */
function separation(weights: DistanceWeights): { accuracy: number; cut: number } {
  const pos: number[] = []
  const neg: number[] = []
  for (const [gloss, ts] of usable) {
    for (let i = 1; i < ts.length; i++) {
      const d = scoreAttempt(ts[i].recording, ts[0].recording, weights).normalizedDistance
      if (Number.isFinite(d)) pos.push(d)
    }
    for (const [otherGloss, others] of usable) {
      if (otherGloss === gloss) continue
      const d = scoreAttempt(ts[0].recording, others[0].recording, weights).normalizedDistance
      if (Number.isFinite(d)) neg.push(d)
    }
  }
  let best = { accuracy: 0, cut: 0 }
  for (const cut of [...pos, ...neg].sort((a, b) => a - b)) {
    const correct = pos.filter((d) => d <= cut).length + neg.filter((d) => d > cut).length
    const accuracy = correct / (pos.length + neg.length)
    if (accuracy > best.accuracy) best = { accuracy, cut }
  }
  return best
}

describeFit('handshape/trajectory weight fit', () => {
  it('searches the weighting and writes the result', () => {
    const results: Array<{ shape: number; accuracy: number; cut: number }> = []
    for (let shape = 0; shape <= 1.0001; shape += 0.1) {
      const w = { shape: Number(shape.toFixed(2)), traj: Number((1 - shape).toFixed(2)) }
      const { accuracy, cut } = separation(w)
      results.push({ shape: w.shape, accuracy, cut })
    }
    const best = results.reduce((a, b) => (b.accuracy > a.accuracy ? b : a))
    const current = results.find((r) => Math.abs(r.shape - DEFAULT_WEIGHTS.shape) < 1e-6)

    writeFileSync(
      join(process.cwd(), 'weight-fit-report.md'),
      [
        '# Handshape / trajectory weight fit',
        '',
        'Generated by `src/scoring/weights.fit.test.ts`. Do not edit by hand.',
        '',
        `Grid search over ${results.length} weightings on ${usable.length} signs`,
        `(≥${MIN_TAKES} takes each) from the calibration corpus. Weights sum to 1.`,
        '',
        '| W_SHAPE | W_TRAJ | separation accuracy |',
        '|---|---|---|',
        ...results.map(
          (r) =>
            `| ${r.shape.toFixed(1)} | ${(1 - r.shape).toFixed(1)} | ` +
            `${(r.accuracy * 100).toFixed(1)}%${
              Math.abs(r.shape - DEFAULT_WEIGHTS.shape) < 1e-6 ? ' ← current' : ''
            }${r.shape === best.shape ? ' ← best' : ''} |`,
        ),
        '',
        `**Best:** W_SHAPE ${best.shape.toFixed(1)} → ${(best.accuracy * 100).toFixed(1)}%`,
        current
          ? `**Current:** W_SHAPE ${current.shape.toFixed(1)} → ${(current.accuracy * 100).toFixed(1)}%`
          : '',
        current
          ? `**Gain from re-fitting:** ${((best.accuracy - current.accuracy) * 100).toFixed(1)} percentage points`
          : '',
        '',
        '## Reading this',
        '',
        'A flat curve means the split barely matters and the 0.7/0.3 choice was',
        'harmless. A sharp peak means it matters and the fitted value should be',
        'adopted. Either way the constant is now measured rather than assumed.',
        '',
        'Same limitation as the score calibration: every take is by one fluent',
        'signer, so this fits the split that separates *correct renditions* from',
        '*different signs*, not the split that best grades a learner.',
        '',
      ].join('\n'),
      'utf8',
    )

    expect(results.length).toBeGreaterThan(5)
    expect(best.accuracy).toBeGreaterThan(0)
  })
})
