"""
Suvana speech service — Sinhala ASR + audio emotion recognition.

Extracted 24 Aug 2026 from the Colab notebook generated by
apps/communicate/notebook-integration/build_notebook.py (WhishperBackend V2,
Lithira's component). The pipeline is a faithful re-housing of the notebook
cells — same models, same functions, same response contract — with the
Colab-specific plumbing replaced:

  ngrok tunnel          -> a persistent host (see Dockerfile / README)
  hardcoded/typed token -> environment configuration
  wide-open /translate  -> optional shared-secret auth (TRANSLATE_API_KEY),
                           the lockdown the original README called for

Contract (unchanged, consumed by apps/communicate app/api/stt/route.ts):
  GET  /           -> {status, device, dtype, emotion_model}
  POST /translate  -> multipart field "audio", optional ?emotion=false
                      {transcription, tokens, emotion: {emotion, confidence},
                       glosses: [], unknown_tokens: [], timings_ms}

Sinhala->gloss mapping deliberately does NOT happen here — it lives in the
web app (lib/nlp/matchers/sinhalaMatcher.ts) against the MongoDB dictionary.

First start downloads ~3.5 GB of model weights (whisper-medium + the Sinhala
LoRA adapter, plus the wav2vec2 fallback unless emotion_clf.joblib is
present). On CPU expect Whisper-medium to be ~10-20x slower than GPU.
"""

import os
import tempfile
import time

import librosa
import numpy as np
import torch
from transformers import (
    Wav2Vec2FeatureExtractor,
    Wav2Vec2ForSequenceClassification,
    WhisperForConditionalGeneration,
    WhisperProcessor,
)
from peft import PeftModel
from sinling import SinhalaTokenizer

from features import extract_features

# ── Configuration (env) ──────────────────────────────────────────────────────
BASE_MODEL = os.environ.get("WHISPER_BASE_MODEL", "openai/whisper-medium")
ADAPTER_ID = os.environ.get("WHISPER_ADAPTER_ID", "SPEAK-ASR/whisper-si-exp-10-medium-all")
EMO_CLF_PATH = os.environ.get("EMOTION_CLF_PATH", "emotion_clf.joblib")
TRANSLATE_API_KEY = os.environ.get("TRANSLATE_API_KEY", "")
CORS_ORIGINS = [o.strip() for o in os.environ.get("CORS_ORIGINS", "*").split(",")]

device = "cuda" if torch.cuda.is_available() else "cpu"
# fp16 roughly halves Whisper's inference time on a GPU and costs no accuracy
# that matters here. CPU stays fp32 — half precision is slower on CPU.
dtype = torch.float16 if device == "cuda" else torch.float32
print(f"Device: {device}  dtype: {dtype}")
if device == "cpu":
    print("WARNING: no GPU. Whisper-medium on CPU is ~10-20x slower.")

# ── Whisper ASR ──
whisper_processor = WhisperProcessor.from_pretrained(BASE_MODEL)
whisper_model = WhisperForConditionalGeneration.from_pretrained(BASE_MODEL)
whisper_model = PeftModel.from_pretrained(whisper_model, ADAPTER_ID)
whisper_model = whisper_model.merge_and_unload().to(device=device, dtype=dtype).eval()
print("Whisper ready")

# ── Sinhala tokenizer ──
# POS tagging was removed in the notebook already: the web app never received
# the result, so it was pure latency. Only the tokenizer is needed.
sinhala_tokenizer = SinhalaTokenizer()
print("Tokenizer ready")

# ── Emotion ──
# Two paths, decided by whether the trained classifier is present.
#
#   emotion_clf.joblib  -> the prosody model from EmotionClassifier.ipynb.
#                          Trained on the four emotions the avatar performs,
#                          and ~20x faster than the transformer below.
#   otherwise           -> the off-the-shelf English wav2vec2 model, so the
#                          service still runs before the classifier artifact
#                          is obtained (ask Lithira for it).
#
# Automatic rather than a flag: forgetting to flip a switch after uploading
# the artifact would silently keep serving the worse model.
USE_TRAINED_EMOTION = os.path.exists(EMO_CLF_PATH)

if USE_TRAINED_EMOTION:
    import joblib

    _emo_bundle = joblib.load(EMO_CLF_PATH)
    emo_model = _emo_bundle["model"]
    EMO_LABELS = _emo_bundle["labels"]
    _m = _emo_bundle["metrics"]
    EMOTION_MODEL_DESC = f"trained-prosody ({_m['algorithm']}, macro-F1 {_m['macro_f1']*100:.1f}%)"
    print(f"Emotion classifier ready — {EMOTION_MODEL_DESC}")
else:
    EMO_ID = "r-f/wav2vec-english-speech-emotion-recognition"
    emo_extractor = Wav2Vec2FeatureExtractor.from_pretrained(EMO_ID)
    emo_model = Wav2Vec2ForSequenceClassification.from_pretrained(EMO_ID).to(device).eval()
    EMOTION_MODEL_DESC = "wav2vec2-english-fallback"
    print("Emotion classifier ready — off-the-shelf English wav2vec2 (fallback)")
    print(f"  Provide {EMO_CLF_PATH} and restart to use the trained model.")

# ── Warm-up ──
# The first inference pays CUDA kernel compilation and lazy weight init, which
# can be 5-10s. Doing it here means the first *real* request doesn't.
_silence = np.zeros(16000, dtype=np.float32)
with torch.inference_mode():
    _f = whisper_processor(_silence, sampling_rate=16000, return_tensors="pt")
    whisper_model.generate(
        _f.input_features.to(device=device, dtype=dtype),
        language="sinhala", task="transcribe", max_new_tokens=8, num_beams=1,
    )
    if not USE_TRAINED_EMOTION:
        emo_model(**emo_extractor(_silence, sampling_rate=16000, return_tensors="pt").to(device))
# librosa and numba compile on first call too — a few hundred ms that would
# otherwise land on the first real request.
if USE_TRAINED_EMOTION:
    _v, _ = extract_features(np.random.randn(16000).astype(np.float32) * 0.01)
    emo_model.predict_proba([_v])
print("Warm-up done — models are hot\n")

# ── Pipeline (verbatim from the notebook) ────────────────────────────────────
# Cap on generated tokens. Whisper defaults to 448, and without a limit a
# short or silent clip can ramble until it hits that ceiling — the single
# biggest source of unpredictable latency. A sign-language utterance is short.
MAX_NEW_TOKENS = 96


def load_audio(path):
    """Decode once, reuse for both models."""
    waveform, _ = librosa.load(path, sr=16000, mono=True)
    return waveform.astype(np.float32)


def transcribe(waveform):
    inputs = whisper_processor(waveform, sampling_rate=16000, return_tensors="pt")
    features = inputs.input_features.to(device=device, dtype=dtype)
    with torch.inference_mode():
        ids = whisper_model.generate(
            features,
            language="sinhala",
            task="transcribe",
            max_new_tokens=MAX_NEW_TOKENS,
            # Greedy. Beam search multiplies decoder passes for accuracy we
            # don't need on short utterances.
            num_beams=1,
        )
    return whisper_processor.batch_decode(ids, skip_special_tokens=True)[0].strip()


def detect_emotion(waveform):
    """
    Returns {"emotion": str, "confidence": float|None}.

    This shape is the contract with the web app — app/api/stt/route.ts reads
    `emotion.emotion` and `emotion.confidence`, and lib/emotion/styles.ts maps
    the label onto an avatar posture. Both branches below honour it, so
    swapping the model changes nothing on the web side.
    """
    if USE_TRAINED_EMOTION:
        # Trim first: the model was trained on trimmed audio, and leading
        # silence would skew duration and pause features away from anything
        # it has seen.
        trimmed, _ = librosa.effects.trim(waveform, top_db=30)
        if trimmed.size < 0.4 * 16000:
            return {"emotion": "neutral", "confidence": None}
        vec, _ = extract_features(trimmed)
        probs = emo_model.predict_proba([vec])[0]
        i = int(np.argmax(probs))
        return {"emotion": EMO_LABELS[i], "confidence": round(float(probs[i]), 3)}

    inputs = emo_extractor(waveform, sampling_rate=16000, return_tensors="pt", padding=True)
    with torch.inference_mode():
        logits = emo_model(**inputs.to(device)).logits
    scores = torch.nn.functional.softmax(logits, dim=1)[0]
    idx = int(torch.argmax(scores))
    return {"emotion": emo_model.config.id2label[idx], "confidence": round(float(scores[idx]), 3)}


def full_pipeline(audio_path, want_emotion=True):
    """
    Audio -> transcript + Sinhala word tokens.

    The Sinhala->gloss lookup is deliberately NOT here — it lives in the web
    app (lib/nlp/matchers/sinhalaMatcher.ts), which handles suffix stripping
    and sound-alike spellings against one MongoDB dictionary editable from
    Dashboard -> Animations. Two dictionaries that could drift apart is one.
    """
    t0 = time.perf_counter()
    waveform = load_audio(audio_path)
    t_load = time.perf_counter()

    text = transcribe(waveform)
    t_asr = time.perf_counter()

    tokens = sinhala_tokenizer.tokenize(text) if text else []
    t_tok = time.perf_counter()

    emotion = detect_emotion(waveform) if want_emotion else {"emotion": "neutral", "confidence": None}
    t_emo = time.perf_counter()

    return {
        "transcription": text,
        "tokens": tokens,
        "emotion": emotion,
        # Kept for older clients; the app prefers `tokens`.
        "glosses": [],
        "unknown_tokens": [],
        "timings_ms": {
            "audio": round((t_load - t0) * 1000),
            "asr": round((t_asr - t_load) * 1000),
            "tokenize": round((t_tok - t_asr) * 1000),
            "emotion": round((t_emo - t_tok) * 1000),
            "total": round((t_emo - t0) * 1000),
        },
    }


# ── HTTP layer ───────────────────────────────────────────────────────────────
from fastapi import FastAPI, File, Query, Request, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

app = FastAPI(title="Suvana speech service")
app.add_middleware(
    CORSMiddleware, allow_origins=CORS_ORIGINS, allow_methods=["*"], allow_headers=["*"]
)


@app.get("/")
def health():
    return {
        "status": "ok",
        "device": device,
        "dtype": str(dtype),
        "emotion_model": EMOTION_MODEL_DESC,
        "auth": "required" if TRANSLATE_API_KEY else "open",
    }


@app.post("/translate")
async def translate(request: Request, audio: UploadFile = File(...), emotion: bool = Query(True)):
    """
    WAV/WebM in, transcript + Sinhala tokens out.

    `?emotion=false` skips the second model pass when the caller doesn't need
    the emotion badge — worth a few hundred ms on CPU.
    """
    # Shared-secret auth, opt-in via TRANSLATE_API_KEY. The Colab notebook ran
    # this endpoint wide open behind an unguessable ngrok URL; a persistent
    # host has a guessable URL, so set the key in any real deployment.
    if TRANSLATE_API_KEY and request.headers.get("x-api-key") != TRANSLATE_API_KEY:
        return JSONResponse(status_code=401, content={"error": "Missing or wrong x-api-key."})

    suffix = os.path.splitext(audio.filename or "")[1] or ".wav"
    with tempfile.NamedTemporaryFile(suffix=suffix, delete=False) as tmp:
        tmp.write(await audio.read())
        tmp_path = tmp.name
    try:
        result = full_pipeline(tmp_path, want_emotion=emotion)
        print("timings:", result["timings_ms"])
        return JSONResponse(content=result)
    except Exception as e:  # noqa: BLE001 — surface the reason to the caller, as the notebook did
        return JSONResponse(status_code=500, content={"error": str(e)})
    finally:
        os.unlink(tmp_path)


@app.on_event("startup")
def register_with_app() -> None:
    """
    Optional self-registration, replacing the notebook's ngrok auto-register:
    the communicate app reads this service's URL from MongoDB, so pointing it
    at a new host is one POST. Set all three env vars to enable:

      PUBLIC_URL           this service's public base URL
      APP_CONFIG_URL       e.g. https://<shell-domain>/communicate/api/config/ngrok-url
      NGROK_UPDATE_SECRET  same value as the app's NGROK_UPDATE_SECRET

    A persistent host has a stable URL, so pasting it once into the app's
    Dashboard -> Settings works just as well; this simply keeps the notebook's
    zero-manual-steps behaviour. Failure is logged, never fatal.
    """
    public_url = os.environ.get("PUBLIC_URL")
    config_url = os.environ.get("APP_CONFIG_URL")
    secret = os.environ.get("NGROK_UPDATE_SECRET")
    if not (public_url and config_url and secret):
        return
    try:
        import requests

        resp = requests.post(
            config_url, json={"url": public_url}, headers={"x-api-key": secret}, timeout=10
        )
        resp.raise_for_status()
        print(f"[registered] {public_url} -> {config_url}")
    except Exception as e:  # noqa: BLE001
        print(f"[register failed, continuing] {e}")


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=int(os.environ.get("PORT", "7860")))
