import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import type { RecordingMeta } from '../vision/types'

// Guards the contract between scripts/build-reference-index.mjs and the app:
// the index is what every view reads instead of 18.5 MB of frames, so if it
// drifts from the reference files on disk the app shows a corpus that is not
// there — or, worse, silently drops a licence.

const refDir = join(process.cwd(), 'public', 'references')
const indexPath = join(process.cwd(), 'public', 'reference-index.json')

const indexExists = existsSync(indexPath)

describe.skipIf(!indexExists)('reference index', () => {
  const index = JSON.parse(readFileSync(indexPath, 'utf8')) as RecordingMeta[]
  const manifest = JSON.parse(readFileSync(join(refDir, 'manifest.json'), 'utf8')) as {
    files: string[]
  }

  it('describes every recording listed in the manifest, exactly once', () => {
    const indexed = index.map((e) => e.file).sort()
    expect(indexed).toEqual([...manifest.files].sort())
  })

  it('carries no frames — that is the entire point of it', () => {
    expect(index.every((e) => !('frames' in e))).toBe(true)
  })

  it('reports a frameCount matching the file it came from', () => {
    // Sampled rather than exhaustive: reading all 362 files is the cost this
    // index exists to avoid, and a drift would not affect only one file.
    const sample = index.filter((_, i) => i % 37 === 0)
    expect(sample.length).toBeGreaterThan(5)
    for (const entry of sample) {
      const raw = JSON.parse(readFileSync(join(refDir, entry.file!), 'utf8')) as {
        frames: unknown[]
      }
      expect(entry.frameCount, `frameCount for ${entry.file}`).toBe(raw.frames.length)
    }
  })

  it('preserves licence and attribution on every dataset recording', () => {
    // CLAUDE.md: two corpora, two licences — kaggle_* is CC0, yohan_* is
    // CC BY-NC-SA 4.0 (non-commercial). The Library credits them from the index
    // alone, so losing these fields here would silently strip attribution.
    const dataset = index.filter((e) => e.source === 'kaggle-dataset' || e.file!.startsWith('yohan_'))
    expect(dataset.length).toBeGreaterThan(0)
    const unlicensed = dataset.filter((e) => !e.licence || !e.attribution)
    expect(unlicensed.map((e) => e.file)).toEqual([])
  })

  it('keeps the fields the picker and the selection rule depend on', () => {
    for (const entry of index) {
      expect(typeof entry.gloss, entry.file).toBe('string')
      expect(entry.gloss.length, entry.file).toBeGreaterThan(0)
      expect(typeof entry.durationMs, entry.file).toBe('number')
      expect(typeof entry.frameCount, entry.file).toBe('number')
      expect(typeof entry.createdAt, entry.file).toBe('string')
    }
  })
})

// A skipped suite is easy to mistake for a passing one, so say why out loud.
describe.skipIf(indexExists)('reference index (not built)', () => {
  it('is missing — run `node scripts/build-reference-index.mjs`', () => {
    expect(indexExists, `${indexPath} does not exist. It is generated by the predev/prebuild/pretest hooks.`).toBe(true)
  })
})
