/**
 * SoundGuard — background execution config plugin
 * ─────────────────────────────────────────────────────────────────────────────
 * Everything the operating system needs to let SoundGuard keep listening while
 * it is not the app on screen. Running this at prebuild time is what makes the
 * next `eas build` produce a binary with the right permissions, the right
 * service declaration and the native glue already wired in — there is nothing
 * for anyone to remember to do by hand, and nothing to re-do after `expo
 * prebuild --clean`.
 *
 * ── What it contributes ──────────────────────────────────────────────────────
 *
 *   Android
 *     • FOREGROUND_SERVICE + FOREGROUND_SERVICE_MICROPHONE — required from
 *       Android 14 to hold a microphone-typed foreground service.
 *     • POST_NOTIFICATIONS — required from Android 13 for the alerts to be seen.
 *     • WAKE_LOCK — the service holds a partial wake lock so Doze cannot stop
 *       delivering audio buffers once the screen goes off.
 *     • VIBRATE — the haptic signatures.
 *     • A `<service …android:foregroundServiceType="microphone">` declaration.
 *     • Three small Java sources (service, native module, package) written into
 *       the app's own package, plus a one-line registration in MainApplication.
 *
 *   iOS
 *     • UIBackgroundModes: audio — keeps the AVAudioSession running when the app
 *       is suspended, which is the equivalent affordance on that platform.
 *
 * ── Why the native source is generated rather than vendored ──────────────────
 *
 * The Java has to live inside the application's own package (it is registered
 * from MainApplication, which is generated), and that package name comes from
 * app.json. Emitting it here keeps a single source of truth: change the package
 * and everything still lines up. The files are written next to the generated
 * MainApplication so they cannot land in a source set Gradle does not compile.
 *
 * The plugin is idempotent in every step — safe to run over an existing
 * `android/` directory as well as a freshly generated one.
 */

const fs = require('fs');
const path = require('path');

const { withAndroidManifest, withDangerousMod, withInfoPlist } = require('expo/config-plugins');

const SERVICE_CLASS = 'SoundGuardForegroundService';
const MODULE_CLASS = 'SoundGuardServiceModule';
const PACKAGE_CLASS = 'SoundGuardServicePackage';

const ANDROID_PERMISSIONS = [
  'android.permission.RECORD_AUDIO',
  'android.permission.MODIFY_AUDIO_SETTINGS',
  'android.permission.FOREGROUND_SERVICE',
  'android.permission.FOREGROUND_SERVICE_MICROPHONE',
  'android.permission.POST_NOTIFICATIONS',
  'android.permission.WAKE_LOCK',
  'android.permission.VIBRATE',
];

// ─── Android manifest ────────────────────────────────────────────────────────

function withManifest(config) {
  return withAndroidManifest(config, (mod) => {
    const manifest = mod.modResults.manifest;

    manifest['uses-permission'] = manifest['uses-permission'] ?? [];
    for (const name of ANDROID_PERMISSIONS) {
      const exists = manifest['uses-permission'].some(
        (entry) => entry && entry.$ && entry.$['android:name'] === name,
      );
      if (!exists) manifest['uses-permission'].push({ $: { 'android:name': name } });
    }

    const application = manifest.application && manifest.application[0];
    if (!application) return mod;

    application.service = application.service ?? [];
    const serviceName = `.${SERVICE_CLASS}`;
    const declared = application.service.find(
      (entry) => entry && entry.$ && entry.$['android:name'] === serviceName,
    );

    const attributes = {
      'android:name': serviceName,
      'android:enabled': 'true',
      'android:exported': 'false',
      // Swiping the app away tears the React instance down, so a service that
      // outlived the task would be a notification with nothing behind it.
      'android:stopWithTask': 'true',
      'android:foregroundServiceType': 'microphone',
    };

    if (declared) Object.assign(declared.$, attributes);
    else application.service.push({ $: attributes });

    return mod;
  });
}

// ─── iOS ─────────────────────────────────────────────────────────────────────

function withIosBackgroundAudio(config) {
  return withInfoPlist(config, (mod) => {
    const modes = new Set(mod.modResults.UIBackgroundModes ?? []);
    modes.add('audio');
    mod.modResults.UIBackgroundModes = Array.from(modes);
    return mod;
  });
}

// ─── Generated Java ──────────────────────────────────────────────────────────

function serviceSource(javaPackage) {
  return `package ${javaPackage};

// Generated by plugins/withSoundGuardBackground.js — do not edit by hand.
//
// A microphone-typed foreground service. Its only job is to make the process
// eligible to read the microphone while SoundGuard is not on screen, and to keep
// the CPU awake so the audio callbacks that feed the recognition pipeline keep
// being scheduled once the screen is off.
//
// It deliberately does no audio work of its own: capture stays in JavaScript,
// where the whole detection pipeline already lives and is already tested.

import android.app.Notification;
import android.app.NotificationChannel;
import android.app.NotificationManager;
import android.app.PendingIntent;
import android.app.Service;
import android.content.Context;
import android.content.Intent;
import android.content.pm.ServiceInfo;
import android.os.Build;
import android.os.IBinder;
import android.os.PowerManager;

// Framework APIs only, deliberately. AndroidX artifacts reach this module
// transitively through React Native, and "transitively available today" is not
// a compile guarantee we want a safety-critical service to depend on.

public class ${SERVICE_CLASS} extends Service {

    public static final String CHANNEL_ID = "soundguard-capture-v1";
    public static final int NOTIFICATION_ID = 8321;

    public static final String ACTION_START = "com.soundguard.capture.START";
    public static final String ACTION_STOP = "com.soundguard.capture.STOP";
    public static final String EXTRA_TITLE = "title";
    public static final String EXTRA_BODY = "body";

    /** Read from the React Native module so the UI can tell the truth. */
    public static volatile boolean isRunning = false;

    /** Ceiling on the wake lock, so a lost release can never flatten a battery. */
    private static final long WAKE_LOCK_TIMEOUT_MS = 12L * 60L * 60L * 1000L;

    private PowerManager.WakeLock wakeLock = null;

    @Override
    public IBinder onBind(Intent intent) {
        return null;
    }

    @Override
    public int onStartCommand(Intent intent, int flags, int startId) {
        if (intent != null && ACTION_STOP.equals(intent.getAction())) {
            shutdown();
            return START_NOT_STICKY;
        }

        String title = "SoundGuard is listening";
        String body = "Monitoring your surroundings. Audio never leaves this phone.";
        if (intent != null) {
            String extraTitle = intent.getStringExtra(EXTRA_TITLE);
            String extraBody = intent.getStringExtra(EXTRA_BODY);
            if (extraTitle != null && extraTitle.length() > 0) title = extraTitle;
            if (extraBody != null && extraBody.length() > 0) body = extraBody;
        }

        try {
            ensureChannel();
            Notification notification = buildNotification(title, body);

            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                startForeground(
                        NOTIFICATION_ID,
                        notification,
                        ServiceInfo.FOREGROUND_SERVICE_TYPE_MICROPHONE);
            } else {
                startForeground(NOTIFICATION_ID, notification);
            }

            acquireWakeLock();
            isRunning = true;
        } catch (Throwable error) {
            // Android 12+ refuses a foreground service started from the
            // background, and Android 14 refuses a microphone-typed one without
            // RECORD_AUDIO. Both are legitimate answers, not crashes: unwind
            // cleanly and let JavaScript fall back to foreground-only listening.
            shutdown();
        }

        // Never sticky. A service restarted by the system without the React
        // instance behind it would show a notification and hear nothing.
        return START_NOT_STICKY;
    }

    @Override
    public void onTaskRemoved(Intent rootIntent) {
        shutdown();
        super.onTaskRemoved(rootIntent);
    }

    @Override
    public void onDestroy() {
        releaseWakeLock();
        isRunning = false;
        super.onDestroy();
    }

    private void shutdown() {
        releaseWakeLock();
        isRunning = false;
        try {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                stopForeground(Service.STOP_FOREGROUND_REMOVE);
            } else {
                stopForeground(true);
            }
        } catch (Throwable ignored) {
            // Already detached.
        }
        stopSelf();
    }

    private void ensureChannel() {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) return;

        NotificationManager manager =
                (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
        if (manager == null || manager.getNotificationChannel(CHANNEL_ID) != null) return;

        NotificationChannel channel =
                new NotificationChannel(
                        CHANNEL_ID,
                        "Background monitoring",
                        NotificationManager.IMPORTANCE_LOW);
        channel.setDescription(
                "The quiet notice Android requires while SoundGuard listens in the background. "
                        + "Alerts themselves arrive on their own channels.");
        channel.setShowBadge(false);
        channel.enableVibration(false);
        channel.enableLights(false);
        channel.setSound(null, null);
        channel.setLockscreenVisibility(Notification.VISIBILITY_PUBLIC);
        manager.createNotificationChannel(channel);
    }

    @SuppressWarnings("deprecation")
    private Notification buildNotification(String title, String body) {
        Notification.Builder builder;
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            builder = new Notification.Builder(this, CHANNEL_ID);
        } else {
            // Pre-channel Android takes its importance from the notification.
            builder = new Notification.Builder(this);
            builder.setPriority(Notification.PRIORITY_LOW);
        }

        builder.setContentTitle(title)
                .setContentText(body)
                .setStyle(new Notification.BigTextStyle().bigText(body))
                // A platform drawable: always present, always the right shape
                // for a status bar, and impossible to get wrong when the app
                // icon changes.
                .setSmallIcon(android.R.drawable.ic_btn_speak_now)
                .setOngoing(true)
                .setShowWhen(false)
                .setCategory(Notification.CATEGORY_SERVICE)
                .setVisibility(Notification.VISIBILITY_PUBLIC);

        PendingIntent contentIntent = buildContentIntent();
        if (contentIntent != null) builder.setContentIntent(contentIntent);

        return builder.build();
    }

    private PendingIntent buildContentIntent() {
        try {
            Intent launch = getPackageManager().getLaunchIntentForPackage(getPackageName());
            if (launch == null) return null;
            launch.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TOP);

            int flags = PendingIntent.FLAG_UPDATE_CURRENT;
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
                flags |= PendingIntent.FLAG_IMMUTABLE;
            }
            return PendingIntent.getActivity(this, 0, launch, flags);
        } catch (Throwable error) {
            return null;
        }
    }

    private void acquireWakeLock() {
        if (wakeLock != null) return;
        try {
            PowerManager manager = (PowerManager) getSystemService(Context.POWER_SERVICE);
            if (manager == null) return;
            PowerManager.WakeLock lock =
                    manager.newWakeLock(PowerManager.PARTIAL_WAKE_LOCK, "SoundGuard::Capture");
            lock.setReferenceCounted(false);
            lock.acquire(WAKE_LOCK_TIMEOUT_MS);
            wakeLock = lock;
        } catch (Throwable ignored) {
            // A device that refuses the wake lock still monitors while awake.
        }
    }

    private void releaseWakeLock() {
        PowerManager.WakeLock lock = wakeLock;
        wakeLock = null;
        if (lock == null) return;
        try {
            if (lock.isHeld()) lock.release();
        } catch (Throwable ignored) {
            // Nothing sensible to do; the timeout would have released it anyway.
        }
    }
}
`;
}

function moduleSource(javaPackage) {
  return `package ${javaPackage};

// Generated by plugins/withSoundGuardBackground.js — do not edit by hand.
//
// The JavaScript-facing handle on the foreground service. Every method resolves
// rather than rejects: refusing to start a service is an ordinary, expected
// answer on modern Android, and a rejected promise in the middle of "start
// monitoring" would turn a graceful degradation into a visible failure.

import android.content.Intent;
import android.os.Build;

import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;

public class ${MODULE_CLASS} extends ReactContextBaseJavaModule {

    public static final String NAME = "SoundGuardBackgroundService";

    public ${MODULE_CLASS}(ReactApplicationContext reactContext) {
        super(reactContext);
    }

    @Override
    public String getName() {
        return NAME;
    }

    @ReactMethod
    public void startService(String title, String body, Promise promise) {
        try {
            ReactApplicationContext context = getReactApplicationContext();
            Intent intent = new Intent(context, ${SERVICE_CLASS}.class);
            intent.setAction(${SERVICE_CLASS}.ACTION_START);
            intent.putExtra(${SERVICE_CLASS}.EXTRA_TITLE, title);
            intent.putExtra(${SERVICE_CLASS}.EXTRA_BODY, body);

            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                context.startForegroundService(intent);
            } else {
                context.startService(intent);
            }
            promise.resolve(true);
        } catch (Throwable error) {
            promise.resolve(false);
        }
    }

    @ReactMethod
    public void stopService(Promise promise) {
        try {
            ReactApplicationContext context = getReactApplicationContext();
            Intent intent = new Intent(context, ${SERVICE_CLASS}.class);
            // stopService rather than an ACTION_STOP start: from Android 8,
            // startService throws when the caller is in the background, and
            // stopping is precisely the thing most likely to be asked for from
            // there. Destroying the service removes its notification and runs
            // onDestroy, which releases the wake lock.
            context.stopService(intent);
        } catch (Throwable ignored) {
            // The service is not running, which is the state we wanted anyway.
        }
        ${SERVICE_CLASS}.isRunning = false;
        promise.resolve(true);
    }

    @ReactMethod
    public void isRunning(Promise promise) {
        promise.resolve(${SERVICE_CLASS}.isRunning);
    }
}
`;
}

function packageSource(javaPackage) {
  return `package ${javaPackage};

// Generated by plugins/withSoundGuardBackground.js — do not edit by hand.

import com.facebook.react.ReactPackage;
import com.facebook.react.bridge.NativeModule;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.uimanager.ViewManager;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class ${PACKAGE_CLASS} implements ReactPackage {

    @Override
    public List<NativeModule> createNativeModules(ReactApplicationContext reactContext) {
        List<NativeModule> modules = new ArrayList<>();
        modules.add(new ${MODULE_CLASS}(reactContext));
        return modules;
    }

    @Override
    public List<ViewManager> createViewManagers(ReactApplicationContext reactContext) {
        return Collections.emptyList();
    }
}
`;
}

// ─── Source emission + MainApplication registration ──────────────────────────

/** Locate the generated MainApplication, whichever source set it landed in. */
function findMainApplication(projectRoot, javaPackage) {
  const relative = javaPackage.split('.').join(path.sep);
  const candidates = [];

  for (const sourceSet of ['java', 'kotlin']) {
    const dir = path.join(projectRoot, 'android', 'app', 'src', 'main', sourceSet, relative);
    candidates.push({ dir, file: path.join(dir, 'MainApplication.kt') });
    candidates.push({ dir, file: path.join(dir, 'MainApplication.java') });
  }

  for (const candidate of candidates) {
    if (fs.existsSync(candidate.file)) return candidate;
  }
  return null;
}

function registerPackage(source, file) {
  if (source.includes(PACKAGE_CLASS)) return source;

  if (file.endsWith('.kt')) {
    // Expo's Kotlin template: `PackageList(this).packages.apply { … }`.
    const anchor = 'PackageList(this).packages.apply {';
    if (source.includes(anchor)) {
      return source.replace(anchor, `${anchor}\n              add(${PACKAGE_CLASS}())`);
    }
    // Older shape, with no apply block to hook into.
    const bare = 'return PackageList(this).packages';
    if (source.includes(bare)) {
      return source.replace(
        bare,
        `return PackageList(this).packages.toMutableList().apply { add(${PACKAGE_CLASS}()) }`,
      );
    }
    return source;
  }

  // Java template.
  const javaAnchor = 'new PackageList(this).getPackages();';
  if (source.includes(javaAnchor)) {
    return source.replace(
      javaAnchor,
      `${javaAnchor}\n      packages.add(new ${PACKAGE_CLASS}());`,
    );
  }
  return source;
}

function withNativeSources(config) {
  return withDangerousMod(config, [
    'android',
    (mod) => {
      const javaPackage = mod.android && mod.android.package;
      if (!javaPackage) {
        throw new Error(
          '[withSoundGuardBackground] android.package is missing from app.json. It is required to place the background service in the application package.',
        );
      }

      const located = findMainApplication(mod.modRequest.projectRoot, javaPackage);
      if (!located) {
        // Nothing to attach to. Better to say so loudly at prebuild than to ship
        // a binary that silently cannot listen in the background.
        throw new Error(
          `[withSoundGuardBackground] Could not find MainApplication for package "${javaPackage}". Run "expo prebuild --clean" and try again.`,
        );
      }

      fs.mkdirSync(located.dir, { recursive: true });

      const files = [
        [`${SERVICE_CLASS}.java`, serviceSource(javaPackage)],
        [`${MODULE_CLASS}.java`, moduleSource(javaPackage)],
        [`${PACKAGE_CLASS}.java`, packageSource(javaPackage)],
      ];

      for (const [name, contents] of files) {
        fs.writeFileSync(path.join(located.dir, name), contents, 'utf8');
      }

      const current = fs.readFileSync(located.file, 'utf8');
      const next = registerPackage(current, located.file);
      if (next !== current) fs.writeFileSync(located.file, next, 'utf8');

      return mod;
    },
  ]);
}

// ─── Entry point ─────────────────────────────────────────────────────────────

module.exports = function withSoundGuardBackground(config) {
  let next = withManifest(config);
  next = withIosBackgroundAudio(next);
  next = withNativeSources(next);
  return next;
};
